title: BitCamp-DevOps-7
description: >-
  Learn how to implement Continuous Delivery (CD) with Microsoft Azure, a third
  party tool. 
template:
  repo: bitcamp-devops-7-template
  name: bitcamp-devops-7
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
